services:
  - type: web
    name: bingohouse
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run serve
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
